# created by eselect-repo

[vGist]
location = /var/db/repos/vGist
sync-type = git
sync-uri = https://github.com/gentoo-mirror/vGist.git
auto-sync = yes
priority = 10

[local]
location = /var/db/repos/local
priority = 20
